fix 30x redirect urls
shuaibiyy/awesome-terraform pull request #240
Opened 2024-01-10 19:57 UTC by chenrui333

2024-01-10 21:22 UTC, antonbabenko requested changes
Minor comments

2024-01-11 14:44 UTC, chenrui333 commented on README.md
> +- [Atom terraform-lookup](https://github.blog/2022-06-08-sunsetting-atom/)
it is not wrong link, it got redirected to the github blog post

2024-01-11 14:45 UTC, chenrui333 commented on README.md
> -- [Infracost + Terraform + GitHub Actions = Automate Cloud Cost Management](https://betterprogramming.pub/infracost-terraform-github-actions-automate-cloud-cost-management-a62b329f2834?sk=495131c5831
I did not know `sk=` is the key

2024-01-11 14:46 UTC, antonbabenko approved these changes

2024-01-11 14:46 UTC, merged